prefix = "streaming-agents"
cloud_provider = "aws"  # or "azure"
cloud_region = "your-region"  # must be a region supported by MongoDB free tier, otherwise Lab2 deployment will not succeed
confluent_cloud_api_key = "your-key"
confluent_cloud_api_secret = "your-secret"
ZAPIER_SSE_ENDPOINT = "https://mcp.zapier.com/api/mcp/s/your-key/sse"  # Lab1
MONGODB_CONNECTION_STRING = "mongodb+srv://cluster0.abc.mongodb.net"  # Lab2
mongodb_username = "your-db-user"  # Lab2
mongodb_password = "your-db-pass"  # Lab2
